<a href="https://colab.research.google.com/github/Ishansingh438/AlmaX-Practice-Set/blob/main/Self_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Search Insert Position: DSA
Given a sorted array of distinct integers and a target value, write a python program to return the index if the target is found. If not, return the index where it would be if it were inserted in order

In [2]:
nums = [1, 3, 5, 6]
target = 5

def searchInsert(nums, target):

  if target in nums:
        return nums.index(target)
  else:
    return len([x for x in nums if x < target])

index = searchInsert(nums, target)
print(index)


2


In [3]:
def findSingleNumber(nums):
    result = 0
    for num in nums:
        result ^= num
    return result

# Example usage
nums = [2, 4, 6, 2, 4]
single_number = findSingleNumber(nums)
print("Single number:", single_number)


Single number: 6


In [4]:
def findMissingNumber(nums):
    n = len(nums)
    missing_number = n
    for i in range(n):
        missing_number ^= i ^ nums[i]
    return missing_number

missing_number = findMissingNumber(nums)
print("Missing number:", missing_number)



Missing number: 7


In [5]:
n=[1,2,3,4,5,45,745,856,846,37,458,47]
n.sort()

print(f"first =  {n[-1]}");
print(f"second =  {n[-2]}");
print(f"third =  {n[-3]}");

first =  856
second =  846
third =  745


In [6]:
nums= [2,2,1]
def singleNumber(nums):
    return 2 * sum(set(nums)) - sum(nums)
print (int(singleNumber(nums)))

1


In [7]:
def searchInsert(nums, target):
    try:
        return nums.index(target)
    except ValueError:
        return len([x for x in nums if x < target])

# Example usage
nums = [1, 3, 5, 6]
target = 5
index = searchInsert(nums, target)
print("Index:", index)


Index: 2


In [8]:
def find_words_greater_than(string,length):
    words = string.split()
    result = []
    for word in words:
      if len(word)> length :
        result.append(word)

    return result

In [9]:
input_string = " i am a professional data analyst"
min_lengths = 4
words = find_words_greater_than(input_string, min_lengths)
print(words)


['professional', 'analyst']


In [10]:
def is_armstrong_number(n):
    # Convert the number to a string to iterate over its digits
    digits = str(n)
    num_digits = len(digits)
    # Calculate the sum of the cubes of the digits
    armstrong_sum = sum(int(digit) ** num_digits for digit in digits)
    # Check if the sum is equal to the original number
    if armstrong_sum == n:
        return True
    else:
        return False

# Read the number of test cases
t = int(input())

# Iterate over the test cases
for _ in range(t):
    # Read the number to check
    number = int(input())
    # Check if it is an Armstrong number
    if is_armstrong_number(number):
        print("It is an ARMSTRONG number")
    else:
        print("It is NOT an ARMSTRONG number")


5
966
It is NOT an ARMSTRONG number


KeyboardInterrupt: ignored

In [1]:
def nextGreaterElement(nums1, nums2):
    stack = []
    next_greater = {}
    result = []

    for num in reversed(nums2):
        while stack and stack[-1] < num:
            stack.pop()

        if stack:
            next_greater[num] = stack[-1]
        stack.append(num)

    for num in nums1:
        result.append(next_greater.get(num, -1))
    return result

# Example usage:
nums1 = [4, 1, 2]
nums2 = [1, 3, 4, 2]
print(nextGreaterElement(nums1, nums2))


[-1, 3, -1]


In [4]:
# Function to find the majority element present in a given list
def findMajorityElement(nums):

    d = {}
    for i in nums:
        d[i] = d.get(i, 0) + 1

    for key, value in d.items():
        if value > len(nums) / 2:
            return key
    return -1

nums = [3,2,3]

result = findMajorityElement(nums)

print(result)

3


In [5]:
nums= [2,1,2]
def largestPerimeter(nums):
  nums.sort(reverse=True)
  for i in range(len(nums)-2):
    if nums[i] < nums[i+1] + nums[i+2]:
      return nums[i] + nums[i+1] + nums[i+2]
      return 0
b= largestPerimeter(nums)
print(b)

5


In [6]:
def plusOne(digits):
  for i in range(len(digits)-1,-1,-1):
    if digits[i]<9:
      digits[i]+=1
      return digits
      digits[i]=0
      return [1]+[0]*len(digits)
digits = [1,2,3]
v =  plusOne(digits)
print(v)

[1, 2, 4]


In [7]:

class py_solution:
   def is_valid_parenthese(self, str1):
        stack = []
        pchar = {"(": ")", "{": "}", "[": "]"}
        for parenthese in str1:
            if parenthese in pchar:
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False
        return len(stack) == 0

print(py_solution().is_valid_parenthese("(){}[]"))
print(py_solution().is_valid_parenthese("()[{)}"))
print(py_solution().is_valid_parenthese("()"))


True
False
True


In [8]:
def calculate_string_length(string):
    length = len(string)
    return length

# Example usage:
input_string = "Hello, world!"
length = calculate_string_length(input_string)
print("Length of the string is:", length)


Length of the string is: 13


In [9]:
def integer_to_string(number, base):
    if number == 0:
        return '0'
    elif number < 0:
        return '-' + integer_to_string(-number, base)
    elif number < base:
        return str(number)
    else:
        return integer_to_string(number // base, base) + str(number % base)

# Example usage:
number = 2835
base = 16
result = integer_to_string(number, base)
print("Number in base", base, ":", result)


Number in base 16 : 1113


In [10]:
n= [1,2,3,4]

def num_sum(n):
  for i in n:
    return sum(n)

r=num_sum(n)
print(r)


10


In [11]:
n = 7
def fibo(n):
    if n <= 1:
        return n
    return fibo(n - 1) + fibo(n - 2)

r= fibo(n)
print(r)

13


In [12]:
year = 2000
def leap_year(year):
  if year%4 ==0 or year%400 ==0:
    return True
  else:
    return False

print(leap_year(year))

True


In [13]:
import numpy as np

my_arr = np.array([1,2,3,4,5,6,7,8,9])
new_array = my_arr.reshape(3,3)

print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Write your code here

string1= 'Emma25 is Data scientist50 and AI Expert'
result = []

string = string1.split()

for word in string:
  if any(char.isalpha() for char in word) and any(char.isdigit() for char in word):
        result.append(word)

print(str(result))

['Emma25', 'scientist50']


In [15]:
def create_string_with_counts(counts):
    return ' '.join([char * count for char, count in counts.items()])

# Test the program
counts = {"f": 1, "o": 2}
output = create_string_with_counts(counts)
print(output)


f oo


In [16]:
v = 12321
def is_palindrome(v):
    num_str = str(v)

    if len(num_str) <= 1:
        return True
    if num_str[0] == num_str[-1]:
        return is_palindrome(num_str[1:-1])
    else:
        return False
print(is_palindrome(v))

True


In [17]:
rows= 5
colms= 5
def print_hollow_rectangle(rows, colms):
    for i in range(rows):
        for j in range(colms):
            if i == 0 or i == rows - 1 or j == 0 or j == colms - 1:
                print("0", end=".")
            else:
                print(" ", end=" ")

            if j < colms - 1:
                print("", end="")

        print()
print_hollow_rectangle(rows, colms)

0.0.0.0.0.
0.      0.
0.      0.
0.      0.
0.0.0.0.0.


In [25]:
lst = [1,2,3,4,5,6,4,4,2,2,4,4,5,43]
def reorder_list(lst, indexes):
  ordered_lst = [None] * len(lst)
  ordered_indexes = [i for i in range(len(indexes))]
  for i, index in enumerate(indexes):
    ordered_lst[index] = lst[i]


  return ordered_lst, ordered_indexes
  ordered_lst, ordered_indexes = reorder_list(lst, indexes)



print("The given list after reordering according to the given indexes list:")
print(ordered_lst)
print()
print("The Index list after reordering:")
print(ordered_indexes)


The given list after reordering according to the given indexes list:


NameError: ignored

In [26]:
import numpy as np

def add_border(arr):
    # Get the shape of the original array
    rows, cols = arr.shape

    # Create a new array with increased dimensions
    new_rows = rows + 2
    new_cols = cols + 2
    new_arr = np.zeros((new_rows, new_cols))

    # Copy the original array into the center of the new array
    new_arr[1:-1, 1:-1] = arr

    return new_arr

# Test the function
arr = np.array([[1., 1., 1., 1.],
                [1., 1., 1., 1.],
                [1., 1., 1., 1.]])

bordered_arr = add_border(arr)
print(bordered_arr)


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
